### ISSUE TITLE
NullReferenceException at Google.Play.AssetDelivery when clearing app's storage

### ISSUE THREAD

**Issue by daniFM** [google/play-unity-plugins#112]
I'm getting this error after a series of steps I describe below
```
NullReferenceException: Object reference not set to an instance of an object.
  at Google.Play.AssetDelivery.Internal.PlayAssetBundleRequestImpl+<CoLoadAssetBundle>d__19.MoveNext () [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) [0x00000] in < 
```

I've implemented Asset Delivery following the documentation, but I'm getting this error every time I do the following:
1. I download my OnDemand bundle at app startup.
2. I close the app and clear all data from the app in settings.
3. I re-open the app and get this error when trying to retrieve my OnDemand bundle.

I've tried the following:
- Re-reying the download throws the `There is already an active request for AssetBundle` error.
- Attempting to cancel the download results in the `PlayAssetBundleRequest` never getting to the state `AssetDeliveryErrorCode.Canceled` , **rendering my app unable to download the asset bundle**.

Is there something else I can do to try to recover my download after this? Is this happening on every project or just in mine?

**Comment by jamcohen** [comment]
Thanks for bringing this to our attention.
How are you testing the app?
Are you using the `Google -> Build and Run` menu option, or are you uploading the app to the Play Developer Console and testing that way?

If you're testing via `Google -> Build and Run`, the app is installed with the [local testing flag](https://developer.android.com/guide/playcore/asset-delivery/test#steps-native-java) enabled. When that is enabled, the app simulates the download, by installing the OnDemand bundle into your app's storage, and copying it over when you retrieve a bundle. When you clear the app's data, you delete the that bundle as well, which could be causing the NullReferenceException.

Still, the code should fail gracefully and give a move informative error message in this case.

If you want to test downloading without having to rebuild the app each time, you can use the `RemoveAssetPack()` method to delete the bundle.

**Comment by JEOptimal** [comment]
We just ran into the exact same issue when testing on an alpha build on Google Play. Caused when clearing the app data.

```
2021-06-05 20:48:59.889 20565 9602 Info Unity Google.Play.Core.Internal.PlayCoreEventHandler:Update()
2021-06-05 20:48:59.889 20565 9602 Info Unity  
2021-06-05 20:48:59.889 20565 9602 Info Unity (Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 39)
2021-06-05 20:48:59.889 20565 9602 Info Unity 
2021-06-05 20:48:59.897 20565 9602 Error Unity NullReferenceException: Object reference not set to an instance of an object.
2021-06-05 20:48:59.897 20565 9602 Error Unity   at Google.Play.AssetDelivery.Internal.PlayAssetBundleRequestImpl+<CoLoadAssetBundle>d__18.MoveNext () [0x00000] in <00000000000000000000000000000000>:0 
2021-06-05 20:48:59.897 20565 9602 Error Unity   at UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) [0x00000] in <00000000000000000000000000000000>:0 
```

**Comment by thanh-nguyen-kim** [comment]
My game has the same issues after manual clear app data.
I discover a workaround by calling "PlayAssetDelivery.RemoveAssetPack(packName);". After that, I can call "PlayAssetDelivery.RetrieveAssetBundleAsync(packName)" and download the bundle as normal.
I think a background service of GooglePlay keep track of downloaded bundle which must be reset before re-download the same one.

**Comment by thanh-nguyen-kim** [comment]
> Thanks for bringing this to our attention.
> How are you testing the app?
> Are you using the `Google -> Build and Run` menu option, or are you uploading the app to the Play Developer Console and testing that way?
> 
> If you're testing via `Google -> Build and Run`, the app is installed with the [local testing flag](https://developer.android.com/guide/playcore/asset-delivery/test#steps-native-java) enabled. When that is enabled, the app simulates the download, by installing the OnDemand bundle into your app's storage, and copying it over when you retrieve a bundle. When you clear the app's data, you delete the that bundle as well, which could be causing the NullReferenceException.
> 
> Still, the code should fail gracefully and give a move informative error message in this case.
> 
> If you want to test downloading without having to rebuild the app each time, you can use the `RemoveAssetPack()` method to delete the bundle.



> Thanks for bringing this to our attention.
> How are you testing the app?
> Are you using the `Google -> Build and Run` menu option, or are you uploading the app to the Play Developer Console and testing that way?
> 
> If you're testing via `Google -> Build and Run`, the app is installed with the [local testing flag](https://developer.android.com/guide/playcore/asset-delivery/test#steps-native-java) enabled. When that is enabled, the app simulates the download, by installing the OnDemand bundle into your app's storage, and copying it over when you retrieve a bundle. When you clear the app's data, you delete the that bundle as well, which could be causing the NullReferenceException.
> 
> Still, the code should fail gracefully and give a move informative error message in this case.
> 
> If you want to test downloading without having to rebuild the app each time, you can use the `RemoveAssetPack()` method to delete the bundle.

I often use Firebase App Distribution and Internal App Sharing to mimic real production environment. This bug always appear after manual clear app data and required a device restart or clear the PlayStore data to redownload the bundle.

**Comment by daniFM** [comment]
> Thanks for bringing this to our attention.
> How are you testing the app?
> Are you using the `Google -> Build and Run` menu option, or are you uploading the app to the Play Developer Console and testing that way?
> 
> If you're testing via `Google -> Build and Run`, the app is installed with the [local testing flag](https://developer.android.com/guide/playcore/asset-delivery/test#steps-native-java) enabled. When that is enabled, the app simulates the download, by installing the OnDemand bundle into your app's storage, and copying it over when you retrieve a bundle. When you clear the app's data, you delete the that bundle as well, which could be causing the NullReferenceException.
> 
> Still, the code should fail gracefully and give a move informative error message in this case.
> 
> If you want to test downloading without having to rebuild the app each time, you can use the `RemoveAssetPack()` method to delete the bundle.

Sorry for coming back to this a bit late.
I'm testing with Internal App Sharing and with the Internal Testing channel in the Play Console, so that shouldn't be the issue.
However, I've found the same results as @thanh-nguyen-kim : calling `RemoveAssetPack()` even if I've just cleared the app's data (even though the pack isn't supposed to be there), solves the issue.

It would be great if `PlayAssetDelivery.RetrieveAssetBundleAsync(packName)` was already protected for this issue or failed gracefully when these conditions are met :)

**Comment by jamcohen** [comment]
Thanks @daniFM for sharing that workaround.

After some investigation we found the issue in the underling Play Core library.
I reached out to that team and they're working towards a fix.

**Comment by GiovanniMeloni** [comment]
Hello! I'm having a similar problem but I'm not sure if its the same, therefore I thought it might be better to comment here instead of opening a new issue.

I've implemented a "Remove Products" button in my game that basically calls the `RemoveAssetPack()` for each assetPack. When testing trough the `Google -> Build and Run` it works fine.

But when I upload to Internal Testing I keep getting the NullReference error:

1. Open the app
2. Click "Remove" button (Calls `RemoveAssetPack()`)
3. Close the app
4. Reopen the app
5. Try to download an asset but error is thrown.

> 06-24 17:49:18.932 15189 15233 E Unity   : NullReferenceException: Object reference not set to an instance of an object.
06-24 17:49:18.932 15189 15233 E Unity   :   at AssetPackAsyncLoader+<AsyncLoader>d__0.MoveNext () [0x00000] in <00000000000000000000000000000000>:0 
06-24 17:49:18.932 15189 15233 E Unity   :   at UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) [0x00000] in <00000000000000000000000000000000>:0 

I've been trying to understand where exactly it fails, and I've discovered that It works just fine until I call the `PlayAssetPackRequestLoadAssetBundleAsync()` method, it returns null as it can be seen in these logs:


> 06-24 17:49:18.853 15189 15233 I Unity   : Calling get asset location, assetPackName: harvester9250_android, path: assetpack/harvester9250_android
06-24 17:49:18.853 15189 15233 I Unity   : UnityEngine.Logger:LogFormat(LogType, String, Object[])
06-24 17:49:18.853 15189 15233 I Unity   : UnityEngine.Debug:LogFormat(String, Object[])
06-24 17:49:18.853 15189 15233 I Unity   : Google.Play.AssetDelivery.Internal.AssetPackManager:GetAssetLocation(String, String)
06-24 17:49:18.853 15189 15233 I Unity   : Google.Play.AssetDelivery.Internal.PlayAssetPackRequestImpl:LoadAssetBundleAsync(String)
06-24 17:49:18.853 15189 15233 I Unity   : <AsyncLoader>d__0:MoveNext()
06-24 17:49:18.853 15189 15233 I Unity   : UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
06-24 17:49:18.853 15189 15233 I Unity   : 
06-24 17:49:18.891 15189 15189 D ViewRootImpl@9c13879[UnityPlayerActivity]: ViewPostIme pointer 0
06-24 17:49:18.929 15189 15233 E Unity   : [MANUAL-LOG][AsyncLoader Script][harvester9250_android] AFTER BUNDLE REQUEST: Content of bundleRequest: 
06-24 17:49:18.929 15189 15233 E Unity   : UnityEngine.Logger:Log(LogType, Object)
06-24 17:49:18.929 15189 15233 E Unity   : <AsyncLoader>d__0:MoveNext()
06-24 17:49:18.929 15189 15233 E Unity   : UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)


After the "Content of BundleRequest:" it should shown the Request, but shows nothing. Heres an log example of what it should be showing: 

> 06-24 17:36:10.286 13860 13895 E Unity   : [MANUAL-LOG][AsyncLoader Script][harvester9250_android] AFTER BUNDLE REQUEST: Content of bundleRequest: UnityEngine.AssetBundleCreateRequest


Any help would be appreciated. If there's need for more information Id be happy to give.

**Comment by jamcohen** [comment]
@daniFM, this was actually an issue with the Play Store service that communicates with the Play Asset Delivery plugin.
It is now fixed in the latest version of the Play Store.

I'm closing this bug, but feel free to reopen it if you're still encountering the issue.

@GiovanniMeloni, I believe your issue is different. I'll follow up in #120.
