### ISSUE TITLE
Concept doubts about Asset Delivery

### ISSUE THREAD

**Issue by AxelCompte** [google/play-unity-plugins#24]
I'm ashamed to admit that I've been stuck in this for a whole week and I'm never felt more stupid.

So I'm gonna ask plain straight:

### Situation 

- I have a scene with only one image in the center.
- I have two sprites in, for example, _Assets/Images/**en**/Test.png_ & _Assets/Images/**es**/Test.png_.
- I want this image to get automatically the correct sprite depending of user's location when that user download the app from Google Play, and **never download** the other unused sprite.

**_Can anyone please explain me how can I archive that?_**

I'm so appreciated for your time, really!

---

### Additional Information

I'm using Unity 2019.3.15f1.
I'm using .NET 4.x and Mono Scripting Backed.
I'm using Google App Bundle, Google Play Delivery/Common/Core 1.1.0 all.
I'm using Asset Bundle Browser.

I tried with Addressables but found that it's not compatible yet.
I tried to convert the folders "_Assets/Images/**en**_" and "_.../**es**_" with two separate bundles and then set them in **Asset Delivery** (Install Time Mode) to finally Build them in my android phone with **Google -> Build & Run**.

I had a look in the samples but I found nothing that clears my problems.

---

### Key Doutbs
- How unity/.aab knows which asset need to get for each language?
- How the gameobject of the Image knows the reference of the correct sprite? Do I need to create some sort of key for it?
- Has the resources / bundles to be in one reserved/specific folder or to be named in an specific nomenclature?
- Does exists some similarity with android "_@drawable/image.png_" -- "_res\drawable-en\image.png_" system?

---
### Testing

- How can I test it? If my phone's language system is in spanish and I set the default Image's sprite with the "_Assets/Images/en/Test.png_" will it get automatically the "._../es/Test.png_" instead when installed?
- Does the "_Google -> Build & Run_" works with all of that o do I need to use "bundletool" option for testing?

Thanks again for everything and sorry to bother you all.

**Comment by jamcohen** [comment]
Thanks for the detailed question. I'm sorry you're running into difficulties.

Unfortunately there's currently no way to configure install time asset packs to automatically do what you describe.

However, what you want to accomplish is possible if you mark your AssetBundles as on-demand and download them using `RetrieveAssetBundleAsync(packName)` when the game starts. You can use [Application.SystemLanguage](https://docs.unity3d.com/ScriptReference/SystemLanguage.html) to get the desired language of the users device, and then map that to the pack matching that language.

To answer your questions:
> How unity/.aab knows which asset need to get for each language?

It won't be able to do this automatically. You'll need to create a `Dictionary` mapping `SystemLanguage` values to AssetBundle names.
>How the gameobject of the Image knows the reference of the correct sprite? Do I need to create some sort of key for it?

You will need to create some way of mapping the gameobject's SpriteRenderer to the name of the sprite within the AssetBundle. What I've done in the past is created a new MonoBehaviour (maybe SpriteReference) that has a string field for the name of the sprite asset. Then I attach that to the gameobject with the language specific SpriteRenderer.

Once the request is returned by `RetrieveAssetBundleAsync(packName)` you'll be able to load a `Sprite` from the request and assign it to whatever component needs it.

Example:
````
public IEnumerator LoadSpanishSprite() {
   var request = RetrieveAssetBundleAsync("es");
   yield return request;
  
   // check for request errors...

   // Get the sprite name associated with the gameobject via a custom SpriteReference class.
   var spriteName = gameObject.GetComponent<SpriteReference>().spriteName;

   // In this case spriteName is "Test.png"
   var testSprite = request.AssetBundle.LoadAsset(spriteName, typeof(Sprite));
   gameObject.GetComponent<SpriteRenderer>().sprite = testSprite;
}
````

> Has the resources / bundles to be in one reserved/specific folder or to be named in an specific nomenclature?

There's no specific nomenclature since in my suggested approach you explicitly download the AssetBundles by name.

>Does exists some similarity with android "@drawable/image.png" -- "res\drawable-en\image.png" system?

No

>How can I test it? If my phone's language system is in spanish and I set the default Image's sprite with the "Assets/Images/en/Test.png" will it get automatically the ".../es/Test.png" instead when installed?

Changing your phone's system language should update `Application.SystemLanguage` so that your code will know which AssetBundle to download.

> Does the "Google -> Build & Run" works with all of that o do I need to use "bundletool" option for testing?

`Google -> Build & Run` will install all of your packs in local-testing mode. Meaning that those on-demand packs will be installed alongside your app, and when requested, the underlying libraries will simulate downloading those packs. You can also tests downloading those packs for real by using [Internal App Sharing](https://developer.android.com/guide/playcore/asset-delivery/test)

Hope that all makes sense. I'm happy to clarify if anything wasn't clear.

**Comment by AxelCompte** [comment]
First of all thanks for this awesome explanation and patience.

I follow your instructions and implemented the code. **It seems to works fine!**

Anyway there's a few doubts about how does it works.

I tested with **two large sprites, each one in its own bundle**, to check the _installed_ app size. The results were:

- Via **apk** and **without** any sprites → **41mb** app size and a **few kb** of user data.
- Via **apk** and **with** sprites → **56mb** app size and a **few kb** of user data.
- Via **aab** with asset bundles containing those sprites →  **36mb** app size and **30mb** of user data, adding a total of **66mb**.

The thing here is that I can delete the user data and it **still working fine**, but that 30mb of user data appears again when I install the .aab.

So my doubts are:

- Do I need to care about this user data? Will it have any impact to a real user one the app is uploaded in Google Play?
- In the testing I can get both en & es sprite versions via Play Asset Delivery. Doesn't that mean that they both exists in the final app size somehow?
- Does the user will requiere internet to check for those bundles?

Sorry for being this newbie, I think I'm missing some important concept about all of this. I can't understand how the user can download only the english sprite verison **before** having the app installed and check the code in it saying that they will need the english version.

It's like I'm stuck in the idea that it must exist some previous configuration somewhere dictating something like "english system language users → download english bundle".

Sorry again for the inconvenience and thank you.

**Comment by jamcohen** [comment]
No apologies necessary. I'm happy to help :)

Regarding the size difference you're seeing with the aab, is that the size after calling `RetrieveAssetBundleAsync(packName)`, or before? 

If you're using `Google -> Build & Run`, the sizes you see may be misleading. Because it installs the app via local-testing mode, the app may be holding multiple copies of the AssetBundles.
I would use [Internal App Sharing](https://developer.android.com/guide/playcore/asset-delivery/test) to get a better idea of exactly how much space your sprites will take up.

> The thing here is that I can delete the user data and it still working fine, but that 30mb of user data appears again when I install the .aab.

My guess is that the AssetBundles are already loaded into memory, so deleting the user data on disk doesn't have an immediate affect. Have you tried calling `RetrieveAssetBundleAsync(packName)` after deleting user data? My guess is that it won't work.

> Do I need to care about this user data? Will it have any impact to a real user one the app is uploaded in Google Play?

I would use [Internal App Sharing](https://developer.android.com/guide/playcore/asset-delivery/test) to determine exactly how much data the user will need to download.

> In the testing I can get both en & es sprite versions via Play Asset Delivery. Doesn't that mean that they both exists in the final app size somehow?

They exist in the app when installing via `Google -> Build and Run` (to make testing locally easier) but if you using Internal App Sharing or otherwise download the app from the play store, those won't exist on the device until they are downloaded via `RetrieveAssetBundleAsync(packName)`.

> Does the user will requiere internet to check for those bundles?

The user will require internet to download the bundles, but if they are already on the device they won't need internet to access them.

>  I can't understand how the user can download only the english sprite version before having the app installed and check the code in it saying that they will need the english version.

Maybe clarifying the user flow will help:
1. The user downloads the app without any language sprites.
2. When the app starts up, your code checks the `Application.SystemLanguage` and calls `RetrieveAssetBundleAsync(packName)` to download the appropriate sprites.
3. Once the sprites are downloaded, they are displayed to the user.

> It's like I'm stuck in the idea that it must exist some previous configuration somewhere dictating something like "english system language users → download english bundle".

There's no magic happening on the Play side. The only "system language → bundle" mapping that exists is the one that you write. From Play's perspective, it has an app with a list of asset packs named "es, en, etc...", but it knows nothing of what language they correspond to.

Does that make sense?

**Comment by AxelCompte** [comment]
Hey, that makes a lot of sense. I don't know why I thought that those assets will be downloaded at the same time of app, so I couldn't get how.

Now that I know that those bundles need to be downloaded **_after_** the app has already installed everything make sense.

Thank you very much for helping me out, for the patiente and those explanations, you're the best.

Cheers!
