### ISSUE TITLE
Will Play Asset Delivery provides sync interface in the future?

### ISSUE THREAD

**Issue by lzqlawrence** [google/play-unity-plugins#27]
So far, there are only RetrieveAssetBundleAsyncInternal and RetrieveAssetPackAsyncInternal for retrieving the assets, will PAD provides some sync methods(eg. AssetBundle.LoadFromFile) for retrieving? Thanks.

**Comment by jamcohen** [comment]
We appended `Async` to those method names to follow Unity's convention, but we don't currently have plans to introduce synchronous methods. Because `RetrieveAssetBundleAsync` and `RetrieveAssetPackAsync` download assets, they can take a pretty long time. Since the amount of time the method can take varies so much (quick if the pack is downloaded, long otherwise), I was worried that adding synchronous methods could cause users to shoot themselves in the foot.
