### ISSUE TITLE
Testing Review flow in Unity

### ISSUE THREAD

**Issue by fer-gamboa** [google/play-unity-plugins#53]
Morning. I am integrating the testing in Unity game [following these steps](https://developer.android.com/guide/playcore/in-app-review/unity). However, my app is still in development and it doesn't work.

I went to check the [testing app review documentation](https://developer.android.com/guide/playcore/in-app-review/test) (which is linked in the Unity page), but it only provides information for Java/Kotlin.

My questions:

- Is the testing app review class `FakeReviewManager` (or any alternative) available to Unity? If so, I'll appreciate any link to a documentation or example.

- Is it possible to test this without having an internal test? (For example, like it is done in _AdMob_ when changing the ID of the ads to a "test id").

Thanks.

**Comment by rafanoel** [comment]
@fer-gamboa thanks for reaching out. 
1. There isn't anything available like `FakeReviewManager` for Unity, but if you want to see the review dialog, the `FakeReviewManager` won't help you since it doesn't make the review dialog show.
2. Unfortunately using the [internal testing track](https://play.google.com/console/about/internal-testing/) is the only way to show the review dialog without hitting the [quota](https://developer.android.com/guide/playcore/in-app-review#quotas), this means that you can show the dialog as many times as you want.

**Comment by fer-gamboa** [comment]
Not even an Alpha test would work for that?

**Comment by rafanoel** [comment]
Using the alpha or beta test track will show the review dialog using the [quota](https://developer.android.com/guide/playcore/in-app-review#quotas) criteria, but the reviews will be private and they won't affect your app's rating. 

If you want the review dialog to be shown every time you execute the review flow, then the only way is using the [internal testing track](https://play.google.com/console/about/internal-testing/).

**Comment by fer-gamboa** [comment]
Thanks @rafanoel. 

Could you please turn this issue into a feature request? I believe that something like a `FakeManager`, and being capable of testing _without_ any type of release (closed track, or internal testing) is extremely important. Especially when one just wants to _see if it works_. Having to do a release every time you want to simply try something is extremely cumbersome and slow.

**Comment by rafanoel** [comment]
We are taking into account the feature request internally, thus closing this issue here.
