### ISSUE TITLE
Packing assets for Google Play Asset Delivery does not shrink app size

### ISSUE THREAD

**Issue by aleksanderwlodarczyk** [google/play-unity-plugins#62]
I am developing Unity AR app with some high poly models and high resolution textures so I want to pack them in bundle to install them at install time (current app size is about 500 MB). 

When I mark the models and textures as bundles, build them and add in google play asset delivery the .aab has the bundles inside and I can see them in Android Studio but the same assets are in the base and the size of app is still the same.

Do I have to manually remove them from project?

**Comment by jamcohen** [comment]
Are those AssetBundles in your StreamingAssets or Resources folder? If so, Unity will include them in the base apk.

You can check if those assets are being included by building an apk through "File -> Build and Run" instead of "Google -> Build and Run". If the AssetBundles are present in the resulting apk then you should try moving those AssetBundles to a different folder.

If the AssetBundles aren't present but the apk size is still large, then those models/textures may be getting referenced (directly or indirectly) by scenes that are included in your build settings. In that case, you should remove all references to those assets in your scene and assign them at runtime when you load the install time AssetBundle.

Does that answer your question?

**Comment by aleksanderwlodarczyk** [comment]
Thank you for answer. It's more clear for me now.

The models and textures are referenced by prefabs in Resources folder. But these prefabs are referenced in scene only by path in scripts. Should I load these textures and models in my Resources prefab in runtime?

**Comment by jamcohen** [comment]
Yes, you've got the right approach. Remove those references from your Resources prefab. Then, at runtime, load the textures and models and assign the references on those prefabs.

**Comment by jamcohen** [comment]
I'm closing this issue, but feel free to reopen if you're still having trouble.
