### ISSUE TITLE
No Assembly definition in com.google.play.billing/runtime

### ISSUE THREAD

**Issue by VirsabiMunk** [google/play-unity-plugins#81]
Just a small compiler performance issue.

**Comment by thanwah** [comment]
Thanks for creating this issue - it's a good point.

We originally had a `Google.Play.Billing.asmdef` file [but had to remove it in order to support a newer version of the Unity IAP package](https://github.com/google/play-unity-plugins/commit/f33c3f3692ddf9c3433d1a4bc92f05be1bb92620).

We will add the .asmdef file back in the future if something changes that enables us to.

**Comment by nguyentrong101094** [comment]
Please add them back, I'm writing a library to simplify using Google Billing. I use assembly definition so if I want to access Google Billing's code, I need reference to Google Billing's assembly definition.
